### ISSUE TITLE
Dev Main App - New User Signup Not Working

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#249]
When you try to create a new User on remote dev environment, you get the error message pasted below.
![new user error](https://user-images.githubusercontent.com/12958622/41253082-3b796f24-6d8d-11e8-9310-a155d860f6e7.png)

But an account is being created. I am allowed to log in using this new user. No email is being sent to the new user that was created

**Comment by gudell** [comment]
Here is what comes up in the Terminal Window when making a new user....

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Object.get (https.js:243:21)
    at reverseGeocode (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/geo-tools/src/geo-tools.js:104:19)
    at async.series.client.index.index (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/server/modules/users/controllers/register.js:126:17)
    at /Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/async/lib/async.js:607:21
    at /Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/async/lib/async.js:246:17
    at iterate (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/async/lib/async.js:162:9)
    at _asyncMap (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/async/lib/async.js:605:19)
    at feed (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/server/modules/users/controllers/register.js:124:15)
    at Layer.handle [as handle_request] (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/express/lib/router/route.js:137:13)
POST /register 500 322.329 ms - 2019
{ Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials m13-v6sm52102iob.86 - gsmtp
    at SMTPConnection._formatError (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:384:15)
    at SMTPConnection._actionAUTHComplete (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:878:30)
    at SMTPConnection.<anonymous> (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:239:22)
    at SMTPConnection._processResponse (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:516:16)
    at SMTPConnection._onData (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:353:10)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials m13-v6sm52102iob.86 - gsmtp',
  responseCode: 535 }
{ Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials b128-v6sm189754itb.3 - gsmtp
    at SMTPConnection._formatError (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:384:15)
    at SMTPConnection._actionAUTHComplete (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:878:30)
    at SMTPConnection.<anonymous> (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:239:22)
    at SMTPConnection._processResponse (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:516:16)
    at SMTPConnection._onData (/Users/gudell/Documents/BarknYapp/bny/www/barknyapp.main/node_modules/smtp-connection/src/smtp-connection.js:353:10)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials b128-v6sm189754itb.3 - gsmtp',
  responseCode: 535 }
